// packages/ohmyui-angular/src/lib/badge/badge.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

export type BadgeVariant = 'success' | 'warning' | 'error' | 'info' | 'neutral';
export type BadgeSize = 'sm' | 'md';

@Component({
  selector: 'ohmyui-badge',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './badge.html',
  styleUrl: './badge.css',
})
export class BadgeComponent {
  @Input() variant: BadgeVariant = 'neutral';
  @Input() size: BadgeSize = 'md';
  @Input() label = '';
}

// packages/ohmyui-react/src/lib/badge/badge.tsx
import styles from './badge.module.css';

export type BadgeVariant = 'success' | 'warning' | 'error' | 'info' | 'neutral';
export type BadgeSize = 'sm' | 'md';

export interface BadgeProps {
  variant?: BadgeVariant;
  size?: BadgeSize;
  label?: string;
}

export function Badge({
  variant = 'neutral',
  size = 'md',
  label = '',
}: BadgeProps) {
  return (
    <span
      className={`${styles['ohmyui-badge']} ${styles[`ohmyui-badge--${variant}`]} ${styles[`ohmyui-badge--${size}`]}`}
    >
      {label}
    </span>
  );
}

export default Badge;
